set (LIBAVCODEC_INCLUDE_DIRS ~/bc-dev/include)
set (LIBAVCODEC_LIBRARY_DIRS /usr/lib/bluecherry/client)
set (LIBAVFORMAT_INCLUDE_DIRS ~/bc-dev/include)
set (LIBAVFORMAT_LIBRARY_DIRS /usr/lib/bluecherry/client)
set (LIBAVUTIL_INCLUDE_DIRS ~/bc-dev/include)
set (LIBAVUTIL_LIBRARY_DIRS /usr/lib/bluecherry/client)
set (LIBSWSCALE_INCLUDE_DIRS ~/bc-dev/include)
set (LIBSWSCALE_LIBRARY_DIRS /usr/lib/bluecherry/client)
set (ENABLE_BREAKPAD OFF)
#set (LINUX_BREAKPAD_DIR ~/bluecherry/bluecherry-client-scripts/dependencies/breakpad)
set (BUILD_TESTING OFF)
set( CMAKE_CXX_FLAGS   -g )
set (LIBSDL2_INCLUDE_DIRS ~/bc-dev/SDL_prefix/include)
set (LIBSDL2_LIBRARY_DIRS ~/bc-dev/SDL_prefix/lib)
set (LIBMPV_INCLUDE_DIRS ~/bc-dev/include)
set (LIBMPV_LIBRARY_DIRS ~/bc-dev/lib)
set (BC_NO_BUNDLED_FFMPEG ON)

