set (LIBAVCODEC_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBAVCODEC_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
set (LIBAVFORMAT_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBAVFORMAT_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
set (LIBAVUTIL_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBAVUTIL_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
set (LIBSWSCALE_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBSWSCALE_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
#set (LINUX_BREAKPAD_DIR ~/bluecherry/bluecherry-client-scripts/dependencies/breakpad)
set (BUILD_TESTING OFF)
set( CMAKE_CXX_FLAGS   -g )
set (LIBSDL2_INCLUDE_DIRS ~/SDL_prefix/include)
set (LIBSDL2_LIBRARY_DIRS ~/SDL_prefix/lib)
