set (LIBAVCODEC_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBAVCODEC_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
set (LIBAVFORMAT_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBAVFORMAT_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
set (LIBAVUTIL_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBAVUTIL_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
set (LIBSWSCALE_INCLUDE_DIRS /usr/lib/bluecherry/client/include)
set (LIBSWSCALE_LIBRARY_DIRS /usr/lib/bluecherry/client/lib)
set (LINUX_BREAKPAD_DIR ~/dev/breakpad)
set (BUILD_TESTING OFF)
set( CMAKE_CXX_FLAGS   -g )
